SELECT * FROM books.favorites;
INSERT INTO favorites (user_id, book_id) VALUES (1, 1), (1, 2);
INSERT INTO favorites (user_id, book_id) VALUES (2, 1), (2, 2), (2, 3);
INSERT INTO favorites (user_id, book_id) VALUES (3, 1), (3, 2), (3, 3), (3, 4);
INSERT INTO favorites (user_id, book_id) VALUES (4, 1), (4, 2), (4, 3), (4, 4), (4, 5);
SELECT * FROM favorites WHERE book_id=3;
DELETE FROM favorites WHERE user_id=2;
INSERT INTO favorites (user_id, book_id) VALUES (5, 2); 
SELECT * FROM favorites WHERE user_id=3;
SELECT * FROM favorites WHERE book_id=5;